# Generated by Django 2.0 on 2019-11-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'url_image',
                'ordering': ['order'],
            },
        ),
    ]
