# Generated by Django 2.0 on 2019-11-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='gender',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female')], default=None, max_length=1, null=True),
        ),
    ]
