# Generated by Django 2.0 on 2019-11-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(null=True)),
                ('date', models.DateTimeField(verbose_name='Date dexpiration')),
            ],
            options={
                'verbose_name': 'event',
                'ordering': ['date'],
            },
        ),
    ]
